# Generated by Django 5.0.1 on 2025-12-18 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_on_hand",
                    models.IntegerField(
                        default=0, help_text="Physical stock available"
                    ),
                ),
                (
                    "quantity_reserved",
                    models.IntegerField(
                        default=0, help_text="Stock reserved in active carts"
                    ),
                ),
                (
                    "warehouse_location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location in warehouse",
                        max_length=100,
                    ),
                ),
                (
                    "last_restock_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time stock was replenished",
                        null=True,
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.IntegerField(
                        default=5, help_text="Alert when stock falls below this number"
                    ),
                ),
                (
                    "sku",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="products.sku",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory",
            },
        ),
    ]
