# Generated by Django 5.0.1 on 2025-12-18 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable order number",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Payment"),
                            ("CONFIRMED", "Payment Confirmed"),
                            ("PROCESSING", "Processing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_name", models.CharField(max_length=255)),
                (
                    "customer_cpf",
                    models.CharField(
                        help_text="Brazilian CPF (###.###.###-##)", max_length=14
                    ),
                ),
                ("customer_phone", models.CharField(max_length=20)),
                ("shipping_street", models.CharField(max_length=255)),
                ("shipping_number", models.CharField(max_length=20)),
                ("shipping_complement", models.CharField(blank=True, max_length=255)),
                ("shipping_neighborhood", models.CharField(max_length=100)),
                ("shipping_city", models.CharField(max_length=100)),
                (
                    "shipping_state",
                    models.CharField(
                        help_text="Two-letter state code (e.g., SP, RJ)", max_length=2
                    ),
                ),
                (
                    "shipping_cep",
                    models.CharField(
                        help_text="Brazilian postal code (#####-###)", max_length=9
                    ),
                ),
                (
                    "subtotal_cents",
                    models.IntegerField(help_text="Items subtotal in cents"),
                ),
                (
                    "shipping_cents",
                    models.IntegerField(default=0, help_text="Shipping cost in cents"),
                ),
                (
                    "discount_cents",
                    models.IntegerField(default=0, help_text="Total discount in cents"),
                ),
                ("total_cents", models.IntegerField(help_text="Final total in cents")),
                ("currency", models.CharField(default="BRL", max_length=3)),
                ("notes", models.TextField(blank=True, help_text="Customer notes")),
                ("tracking_code", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price_cents",
                    models.IntegerField(
                        help_text="Price per unit at time of purchase (in cents)"
                    ),
                ),
                (
                    "line_total_cents",
                    models.IntegerField(
                        help_text="Total for this line item (in cents)"
                    ),
                ),
                (
                    "product_snapshot",
                    models.JSONField(
                        default=dict, help_text="Product details at time of purchase"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="products.sku",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_number"], name="orders_orde_order_n_f3ada5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_email"], name="orders_orde_custome_ca0107_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "created_at"], name="orders_orde_status_25e057_idx"
            ),
        ),
    ]
