# Generated by Django 5.0.1 on 2025-12-18 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Unique key to prevent duplicate charges",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Payment provider name (e.g., mercadopago, asaas)",
                        max_length=50,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Transaction ID from payment provider",
                        max_length=255,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("BOLETO", "Boleto"),
                            ("CREDIT_CARD", "Credit Card"),
                            ("DEBIT_CARD", "Debit Card"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "amount_cents",
                    models.IntegerField(help_text="Payment amount in cents"),
                ),
                (
                    "fees_cents",
                    models.IntegerField(
                        blank=True, help_text="Provider fees in cents", null=True
                    ),
                ),
                ("currency", models.CharField(default="BRL", max_length=3)),
                (
                    "pix_qr_code",
                    models.TextField(blank=True, help_text="Pix QR code data"),
                ),
                (
                    "pix_copy_paste",
                    models.TextField(blank=True, help_text="Pix copy-paste code"),
                ),
                ("boleto_url", models.URLField(blank=True, help_text="Boleto PDF URL")),
                (
                    "boleto_barcode",
                    models.CharField(
                        blank=True, help_text="Boleto barcode number", max_length=255
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Payment expiration (for Pix/Boleto)",
                        null=True,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was confirmed", null=True
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw response from payment provider",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "status"],
                        name="payments_pa_order_i_ed562a_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_transaction_id"],
                        name="payments_pa_provide_a7d2ea_idx",
                    ),
                    models.Index(
                        fields=["method", "status"],
                        name="payments_pa_method_e1d85f_idx",
                    ),
                ],
            },
        ),
    ]
