# Generated by Django 5.0.1 on 2025-12-18 02:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Magic: The Gathering, Pokemon",
                        max_length=100,
                    ),
                ),
                (
                    "set_name",
                    models.CharField(
                        blank=True, help_text="Expansion or set name", max_length=200
                    ),
                ),
                (
                    "tcg_number",
                    models.CharField(
                        blank=True, help_text="Collector number", max_length=50
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMMON", "Common"),
                            ("UNCOMMON", "Uncommon"),
                            ("RARE", "Rare"),
                            ("MYTHIC", "Mythic Rare"),
                            ("SPECIAL", "Special"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["brand", "set_name"],
                        name="products_pr_brand_427d13_idx",
                    ),
                    models.Index(
                        fields=["rarity"], name="products_pr_rarity_3e126f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku_code",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("MINT", "Mint"),
                            ("NEAR_MINT", "Near Mint"),
                            ("LIGHTLY_PLAYED", "Lightly Played"),
                            ("PLAYED", "Played"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="NEAR_MINT",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("PT", "Portuguese"),
                            ("ES", "Spanish"),
                            ("JP", "Japanese"),
                            ("KO", "Korean"),
                        ],
                        default="EN",
                        max_length=5,
                    ),
                ),
                ("is_foil", models.BooleanField(default=False)),
                ("price_cents", models.IntegerField(help_text="Price in BRL cents")),
                (
                    "sale_price_cents",
                    models.IntegerField(
                        blank=True,
                        help_text="Sale price in BRL cents (if on sale)",
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="BRL", max_length=3)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU",
                "verbose_name_plural": "SKUs",
                "ordering": ["price_cents"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="products_sk_product_ea0deb_idx",
                    ),
                    models.Index(
                        fields=["condition", "language"],
                        name="products_sk_conditi_3fb40e_idx",
                    ),
                ],
            },
        ),
    ]
